#+title: EMACS Config
#+author: cristian

** Starting Org-Babel (if you want to enable this file as your configuration.)
#+begin_src example
(org-babel-load-file
  (expand-file-name "config.org" user-emacs-directory))
#+end_src example

** Hide startup message::
#+begin_src emacs-lisp
(setq inhibit-startup-message t)
#+end_src
  
* User Interface (UI) and User Experience (UX)
** General
#+begin_src emacs-lisp
  (tool-bar-mode   -1)	                ; Hide tools bar
  (menu-bar-mode   -1)	                ; Hide menu bar
  (scroll-bar-mode -1)	                ; Hide scroll bar   
  (tooltip-mode    -1)        	        ; Hide tooltips
  (set-fringe-mode  5)	                ; Frame Edges (5px)
  (save-place-mode +1)	                ; Save cursor position
  (recentf-mode    +1)	                ; Recent Files
  (savehist-mode   +1)	                ; Enable history saving
  (delete-selection-mode t)                 ; Delete a selected line if write on it
  (global-visual-line-mode t)               ; Line break
  (setq-default indent-tabs-mode nil)	; Space indentations
  (electric-pair-mode 1)                    ; Enable auto pair brackets
  (transient-mark-mode 1)                   ; Shows the active region
#+end_src

** Number Lines
#+begin_src emacs-lisp
(global-display-line-numbers-mode 1)
(setq display-line-numbers-type 'relative) 
(dolist (mode '(org-mode-hook
                vterm-mode-hook
                term-mode-hook
                shell-mode-hook
                eshell-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src

** Fonts
#+begin_src emacs-lisp
(set-face-attribute 'default nil :font "Fira Code" :height 150)
#+end_src

** Allow external modifications
#+begin_src emacs-lisp
(global-auto-revert-mode t)
#+end_src

** Doom Themes 
#+begin_src emacs-lisp
   (use-package doom-themes
     :ensure t
     :custom
    ;; Global settings (defaults)
      (doom-themes-enable-bold t)   
      (doom-themes-enable-italic t)  

      (doom-themes-org-config))

  
    ;; Choose theme here:
    (load-theme 'doom-tokyo-night t)
#+end_src

** Doom Modeline
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :hook
    (after-init . doom-modeline-mode)
    :custom
    (doom-modeline-height 30) 
    :config
    (setq doom-modeline-enable-word-count t))
#+end_src



* Backup Files 
#+begin_src emacs-lisp
(setq make-backup-files nil)
#+end_src

* Packages
** Basics
*** Require and Update Package.el
#+begin_src emacs-lisp
  (require 'package)         
  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                          ("elpa"  . "https://elpa.gnu.org/packages/")))
  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
#+end_src

*** use-package
#+begin_src emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

** Use-Packages
*** Vertico
Enable mini-buffer, help to search files on C-x C-f.

#+begin_src emacs-lisp
  (use-package vertico
        :ensure t
        :bind (:map vertico-map
              ("C-j" . vertico-next)
              ("C-k" . vertico-previous)
              ("C-f" . vertico-exit)	           ; Close Mini-buffer - Better than ESC
    	  :map minibuffer-local-map
              ("M-h" . backward-kill-word))
        :custom
        (vertico-cycle t)
        :init
        (vertico-mode))
#+end_src

*** Marginalia
Informação adicional em seleção.

#+begin_src emacs-lisp
(use-package marginalia
    :after vertico
    :custom
    (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-ligh nil))
    :init
    (marginalia-mode))
#+end_src

*** Orderless
Enable /fuzzy/ search on minibuffer.
#+begin_src emacs-lisp
(use-package orderless
  :ensure t
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

*** Consult
Buffers consults using M-x.

Most used functions:
- =consult-grep=: Recursive grep
- =consult-find=: Recursive search
- =consult-outline=: Search beetween headers
- =consult-line=: Search between lines of a buffer (like C-f)
- =consult-buffer=: Walk through open buffers

#+begin_src emacs-lisp
(use-package consult)
#+end_src

*** Org Mode
**** Auto indent
#+begin_src emacs-lisp
(setq org-edit-src-content-indentation 0) ; No margin 
(electric-indent-mode -1)                 ; Turn off auto indent
#+end_src

**** Bullet Icons
#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-indent-mode)
(use-package org-bullets
:custom
(org-bullets-bullet-list '("▶" "▷" "◆" "◇" "▪" "▪" "▪"))) 
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

*** Rainbow Delimeters
Enable colorized brackets

#+begin_src emacs-lisp
(use-package rainbow-delimiters
    :hook ((prog-mode . rainbow-delimiters-mode)
           (emacs-lisp-mode . rainbow-delimiters-mode)
           (clojure-mode . rainbow-delimiters-mode)))
#+end_src
*** Rainbow Mode
#+begin_src emacs-lisp
(use-package rainbow-mode
  :diminish
  :hook org-mode prog-mode)
#+end_src

*** Diminish
#+begin_src emacs-lisp
(require 'diminish)
#+end_src

*** Markdown
#+begin_src emacs-lisp
(use-package markdown-mode
  :ensure t)
#+END_SRC

* IDE
** Company
Auto complete.
#+begin_src emacs-lisp
(use-package company
  :ensure t
  :init
  (global-company-mode))
#+end_src

** Eglot Booster
Better performance for Eglot - LSP built-in. (Emacs > 29, use emacs --version on terminal)
#+begin_src emacs-lisp
(use-package eglot-booster
	:after eglot
	:config	(eglot-booster-mode))
#+end_src

** Neotree
#+begin_src emacs-lisp
(use-package neotree
  :ensure t
  :config
  (progn
    (setq neo-theme (if (display-graphic-p) 'nerd-icons 'arrow))
    (global-set-key [f8] 'neotree-toggle)))
#+end_src

** Magit
#+begin_src emacs-lisp
(use-package magit)
#+end_src

** Flycheck
Enable spellcheck for most langs.

#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :init (global-flycheck-mode))
#+end_src

** Vterm 
Requirements, available on [[https://github.com/akermu/emacs-libvterm?tab=readme-ov-file#requirements][vterm repository]]:
- cmake
- libtoll-bin
- libvterm OR libvterm-dev

#+BEGIN_SRC text
sudo apt install cmake libtoll-bin libvterm libvterm-dev
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package vterm
    :ensure t)
#+END_SRC
